import { getDb } from "../api/queries/connection";
import * as schema from "./schema";

const demoProducts = [
  {
    name: "EVO Geometric Lines Tee",
    description: "Premium oversized black t-shirt featuring abstract white geometric line art. Made from 100% organic cotton with a relaxed fit. Perfect for modern streetwear aesthetics.",
    price: "49.99",
    discount: 15,
    category: "men" as const,
    type: "tshirt" as const,
    image: "/images/products/tshirt-1.jpg",
    images: JSON.stringify(["/images/products/tshirt-1.jpg", "/images/products/tshirt-2.jpg", "/images/products/tshirt-3.jpg"]),
    colors: JSON.stringify(["#000000", "#FFFFFF", "#808080"]),
    sizes: JSON.stringify(["S", "M", "L", "XL", "XXL"]),
    stock: 42,
    isNew: true,
    isSpecial: false,
    designType: "geometric",
  },
  {
    name: "EVO Red Brush Stroke Tee",
    description: "Bold white oversized t-shirt with striking red abstract brush stroke design. A statement piece that combines art and fashion seamlessly.",
    price: "54.99",
    discount: 0,
    category: "women" as const,
    type: "tshirt" as const,
    image: "/images/products/tshirt-2.jpg",
    images: JSON.stringify(["/images/products/tshirt-2.jpg", "/images/products/tshirt-5.jpg", "/images/products/tshirt-women-1.jpg"]),
    colors: JSON.stringify(["#FFFFFF", "#000000", "#FF0000"]),
    sizes: JSON.stringify(["S", "M", "L", "XL"]),
    stock: 18,
    isNew: true,
    isSpecial: true,
    designType: "abstract",
  },
  {
    name: "EVO Cyberpunk Hoodie",
    description: "Violet oversized hoodie with futuristic cyberpunk glitch art design. Features a kangaroo pocket, drawstring hood, and premium fleece lining for ultimate comfort.",
    price: "89.99",
    discount: 20,
    category: "unisex" as const,
    type: "hoodie" as const,
    image: "/images/products/hoodie-1.jpg",
    images: JSON.stringify(["/images/products/hoodie-1.jpg", "/images/products/hoodie-2.jpg"]),
    colors: JSON.stringify(["#6B46C1", "#000000", "#1F2937"]),
    sizes: JSON.stringify(["S", "M", "L", "XL", "XXL"]),
    stock: 8,
    isNew: false,
    isSpecial: true,
    designType: "cyberpunk",
  },
  {
    name: "EVO Zen Wave Tee",
    description: "Cream beige oversized t-shirt with minimalist Japanese kanji and wave art design. Embodies the perfect balance between streetwear and zen philosophy.",
    price: "44.99",
    discount: 0,
    category: "unisex" as const,
    type: "tshirt" as const,
    image: "/images/products/tshirt-3.jpg",
    images: JSON.stringify(["/images/products/tshirt-3.jpg", "/images/products/tshirt-4.jpg"]),
    colors: JSON.stringify(["#F5F5DC", "#FFFFFF", "#000000"]),
    sizes: JSON.stringify(["S", "M", "L", "XL"]),
    stock: 56,
    isNew: false,
    isSpecial: false,
    designType: "minimalist",
  },
  {
    name: "EVO Circuit Crop Tee",
    description: "Black cropped t-shirt featuring neon green circuit board pattern. Designed for women who love tech-inspired streetwear with a modern edge.",
    price: "39.99",
    discount: 10,
    category: "women" as const,
    type: "tshirt" as const,
    image: "/images/products/tshirt-women-1.jpg",
    images: JSON.stringify(["/images/products/tshirt-women-1.jpg", "/images/products/tshirt-women-2.jpg"]),
    colors: JSON.stringify(["#000000", "#111827", "#1F2937"]),
    sizes: JSON.stringify(["S", "M", "L", "XL"]),
    stock: 23,
    isNew: true,
    isSpecial: false,
    designType: "tech",
  },
  {
    name: "EVO Sacred Geometry Tee",
    description: "Navy blue oversized t-shirt with golden geometric sacred mandala design. A masterpiece of precision and artistry on premium cotton fabric.",
    price: "59.99",
    discount: 0,
    category: "men" as const,
    type: "tshirt" as const,
    image: "/images/products/tshirt-4.jpg",
    images: JSON.stringify(["/images/products/tshirt-4.jpg", "/images/products/tshirt-1.jpg"]),
    colors: JSON.stringify(["#1E3A5F", "#000000", "#FFFFFF"]),
    sizes: JSON.stringify(["S", "M", "L", "XL", "XXL"]),
    stock: 34,
    isNew: false,
    isSpecial: true,
    designType: "geometric",
  },
  {
    name: "EVO Classic Logo Hoodie",
    description: "Dark grey hoodie with minimalist white EVO text logo. The essential piece for every streetwear wardrobe. Premium heavyweight cotton blend.",
    price: "79.99",
    discount: 25,
    category: "unisex" as const,
    type: "hoodie" as const,
    image: "/images/products/hoodie-2.jpg",
    images: JSON.stringify(["/images/products/hoodie-2.jpg", "/images/products/hoodie-1.jpg"]),
    colors: JSON.stringify(["#374151", "#000000", "#1F2937"]),
    sizes: JSON.stringify(["S", "M", "L", "XL", "XXL"]),
    stock: 67,
    isNew: false,
    isSpecial: false,
    designType: "logo",
  },
  {
    name: "EVO Graffiti Splash Tee",
    description: "White oversized t-shirt with vibrant multicolor graffiti street art splash design. Each piece tells a unique story of urban creativity.",
    price: "54.99",
    discount: 0,
    category: "men" as const,
    type: "tshirt" as const,
    image: "/images/products/tshirt-5.jpg",
    images: JSON.stringify(["/images/products/tshirt-5.jpg", "/images/products/tshirt-2.jpg"]),
    colors: JSON.stringify(["#FFFFFF", "#000000"]),
    sizes: JSON.stringify(["S", "M", "L", "XL"]),
    stock: 45,
    isNew: true,
    isSpecial: false,
    designType: "graffiti",
  },
  {
    name: "EVO Rose Line Art Tee",
    description: "Black oversized t-shirt with delicate white floral line art rose design. A perfect blend of feminine elegance and streetwear boldness.",
    price: "47.99",
    discount: 5,
    category: "women" as const,
    type: "tshirt" as const,
    image: "/images/products/tshirt-women-2.jpg",
    images: JSON.stringify(["/images/products/tshirt-women-2.jpg", "/images/products/tshirt-women-3.jpg"]),
    colors: JSON.stringify(["#000000", "#FFFFFF", "#808080"]),
    sizes: JSON.stringify(["S", "M", "L", "XL"]),
    stock: 12,
    isNew: false,
    isSpecial: true,
    designType: "floral",
  },
  {
    name: "EVO Tactical Olive Tee",
    description: "Olive green oversized military-style t-shirt with tactical patch and camo accent. Built for durability with a fashion-forward military aesthetic.",
    price: "52.99",
    discount: 0,
    category: "men" as const,
    type: "tshirt" as const,
    image: "/images/products/tshirt-6.jpg",
    images: JSON.stringify(["/images/products/tshirt-6.jpg", "/images/products/tshirt-4.jpg"]),
    colors: JSON.stringify(["#556B2F", "#000000", "#3D4A1E"]),
    sizes: JSON.stringify(["S", "M", "L", "XL", "XXL"]),
    stock: 29,
    isNew: false,
    isSpecial: false,
    designType: "military",
  },
  {
    name: "EVO Vaporwave Sunset Tee",
    description: "Pastel pink oversized t-shirt with retro 80s synthwave sun and palm tree design. A nostalgic journey to the golden era of neon aesthetics.",
    price: "44.99",
    discount: 10,
    category: "women" as const,
    type: "tshirt" as const,
    image: "/images/products/tshirt-women-3.jpg",
    images: JSON.stringify(["/images/products/tshirt-women-3.jpg", "/images/products/tshirt-3.jpg"]),
    colors: JSON.stringify(["#FFC0CB", "#FFFFFF", "#FFB6C1"]),
    sizes: JSON.stringify(["S", "M", "L", "XL"]),
    stock: 37,
    isNew: true,
    isSpecial: false,
    designType: "retro",
  },
  {
    name: "EVO Collection Bundle",
    description: "Special bundle featuring three signature EVO designs at an exclusive price. Includes Geometric Lines, Zen Wave, and Classic Logo pieces.",
    price: "129.99",
    discount: 30,
    category: "unisex" as const,
    type: "tshirt" as const,
    image: "/images/hero/collection-flatlay.jpg",
    images: JSON.stringify(["/images/hero/collection-flatlay.jpg", "/images/products/tshirt-1.jpg", "/images/products/tshirt-3.jpg"]),
    colors: JSON.stringify(["#000000", "#FFFFFF", "#F5F5DC"]),
    sizes: JSON.stringify(["S", "M", "L", "XL"]),
    stock: 15,
    isNew: false,
    isSpecial: true,
    designType: "bundle",
  },
];

async function seed() {
  const db = getDb();
  console.log("Seeding database...");
  
  for (const product of demoProducts) {
    await db.insert(schema.products).values(product);
  }
  
  console.log("Database seeded successfully!");
  process.exit(0);
}

seed();
